plugins {
    id 'java'
    id 'com.diffplug.spotless'
}

group = 'org.apache.flink'
version = '1.20'

ext {
    javaVersion = '17'
    flinkVersion = '1.20.1'
    scalaBinaryVersion = '2.12'
    jacksonVersion = '2.11.2'
    log4jVersion = '2.17.1'
    junitVersion = '4.13'
}

spotless {
    format 'misc', {
        target '*.gradle', '*.md', '.gitignore'

        trimTrailingWhitespace()
        indentWithSpaces(4)
        endWithNewline()
    }

    // TODO reenable when I fix the Java formatting issues
    // java {
    //     googleJavaFormat().aosp()
    //     importOrder('org.apache.flink', 'org.apache.flink.shaded', '', 'javax', 'java', '\\#')
    //     removeUnusedImports()
    //     targetExclude("**/generated*/**/*.java")
    // }
}

repositories {
    // for access from China, you may need to uncomment this line
    // maven { url 'https://maven.aliyun.com/repository/public/' }
    mavenCentral()

    maven {
        url "https://mvnrepository.com/artifact/"
    }

    maven {
        url "https://repository.apache.org/content/repositories/snapshots/"
        mavenContent {
            snapshotsOnly()
        }
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    jvmArgs '--add-opens=java.base/java.util=ALL-UNNAMED'
}

sourceCompatibility = javaVersion
targetCompatibility = javaVersion
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// declare where to find the dependencies of your project
repositories {
    // for access from China, you may need to uncomment this line
    // maven { url 'https://maven.aliyun.com/repository/public/' }
    mavenCentral()
    maven {
        url "https://repository.apache.org/content/repositories/snapshots/"
        mavenContent {
            snapshotsOnly()
        }
    }
}

// common set of dependencies
dependencies {
    implementation "org.apache.flink:flink-clients:${flinkVersion}"
    implementation "org.apache.flink:flink-java:${flinkVersion}"
    implementation "org.apache.flink:flink-streaming-java:${flinkVersion}"

    // allows using Flink's web UI when running in the IDE:
    implementation "org.apache.flink:flink-runtime-web:${flinkVersion}"
    // allow using RocksDB when running in the IDE:
    implementation "org.apache.flink:flink-statebackend-rocksdb:${flinkVersion}"

    implementation "org.apache.logging.log4j:log4j-slf4j-impl:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-api:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-core:${log4jVersion}"

    plugins.withId('java-test-fixtures') {
        testFixturesImplementation "org.apache.flink:flink-clients:${flinkVersion}"
        testFixturesImplementation "org.apache.flink:flink-java:${flinkVersion}"
        testFixturesImplementation "org.apache.flink:flink-streaming-java:${flinkVersion}"

        testFixturesImplementation 'org.assertj:assertj-core:3.20.2'

        testFixturesImplementation "org.apache.logging.log4j:log4j-slf4j-impl:${log4jVersion}"
        testFixturesImplementation "org.apache.logging.log4j:log4j-api:${log4jVersion}"
        testFixturesImplementation "org.apache.logging.log4j:log4j-core:${log4jVersion}"
    }

    // common set for testing
    testImplementation "junit:junit:${junitVersion}"
    testImplementation "org.apache.flink:flink-streaming-java:${flinkVersion}:tests"
    testImplementation "org.apache.flink:flink-runtime:${flinkVersion}:tests"
    testImplementation "org.apache.flink:flink-test-utils-junit:${flinkVersion}"
    testImplementation "org.apache.flink:flink-test-utils:${flinkVersion}"
}

// add solution source dirs
sourceSets {
    main.java.srcDirs += 'src/solution/java'

    // Add shadow configuration to runtime class path so that the
    // dynamically-generated tasks by IntelliJ are able to run and have
    // all dependencies they need. (Luckily, this does not influence what
    // ends up in the final shadowJar.)
    // TODO main.runtimeClasspath += configurations.shadow

    // TODO test.compileClasspath += configurations.shadow
    // TODO test.runtimeClasspath += configurations.shadow
}

tasks.withType(Jar).configureEach {
    archiveBaseName = "${project.parent.name}-${project.name}"
    manifest {
        attributes 'Built-By': System.getProperty('user.name'),
                'Build-Jdk': System.getProperty('java.version')
    }
}
