plugins {
    id 'flink-training-application'
}

group = 'com.ververica.flink.training.bootcamp'

tasks.register('testSolutions', Test) {
    group = 'verification'
    filter { excludeTestsMatching("*.exercises.*") }
}
tasks.named('test', Test) {
    filter { includeTestsMatching("*.exercises.*") }
}

dependencies {
    implementation project(':common')
    testImplementation testFixtures(project(':common'))
}
