plugins {
    id 'flink-training-application'
    id 'com.github.johnrengelman.shadow'
}

// Create a zip of just the required files for students.
tasks.register('zip', Zip) {
    // Run tests before...

    archiveFileName = "flink-training-developer.zip"
    destinationDirectory = layout.buildDirectory

    from(layout.projectDirectory)
    exclude("**/build")
    exclude("**/.*")
}

// Set up so build will create the bootcamp zip file
tasks.assemble {
    // TODO - depends on solution tests passing.
    dependsOn(zip)
}

// TODO - move to flink-training-application.gradle, since likely
// needed for all three targets (bootcamp, developer, advanced)?
dependencies {
    // allows using Flink's web UI when running in the IDE:
    implementation "org.apache.flink:flink-runtime-web:${flinkVersion}"
    // allow using RocksDB when running in the IDE:
    implementation "org.apache.flink:flink-statebackend-rocksdb:${flinkVersion}"
}
