plugins {
    id 'flink-training'
    id 'application'

    // TODO - maybe only for troubleshooting, where we need to build uber jar
    // to deploy to the cluster???

    // id 'com.github.johnrengelman.shadow'
}

dependencies {
    // allows using Flink's web UI when running in the IDE:
    implementation "org.apache.flink:flink-runtime-web:${flinkVersion}"
    // allow using RocksDB when running in the IDE:
    implementation "org.apache.flink:flink-statebackend-rocksdb:${flinkVersion}"
}
