plugins {
    id 'java'
    id 'com.diffplug.spotless'
}

group = 'org.apache.flink'
version = '1.20'

ext {
    javaVersion = '17'
    flinkVersion = '1.20.1'
    jacksonVersion = '2.11.2'
    log4jVersion = '2.17.1'
    junitVersion = '4.13'
}

spotless {
    format 'misc', {
        target '*.gradle', '*.md', '.gitignore'

        trimTrailingWhitespace()
        indentWithSpaces(4)
        endWithNewline()
    }

    format 'markdown', {
        target '*.md'

        licenseHeader '<!--\n' +
                'Licensed to the Apache Software Foundation (ASF) under one\n' +
                'or more contributor license agreements.  See the NOTICE file\n' +
                'distributed with this work for additional information\n' +
                'regarding copyright ownership.  The ASF licenses this file\n' +
                'to you under the Apache License, Version 2.0 (the\n' +
                '"License"); you may not use this file except in compliance\n' +
                'with the License.  You may obtain a copy of the License at\n' +
                '\n' +
                '  http://www.apache.org/licenses/LICENSE-2.0\n' +
                '\n' +
                'Unless required by applicable law or agreed to in writing,\n' +
                'software distributed under the License is distributed on an\n' +
                '"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY\n' +
                'KIND, either express or implied.  See the License for the\n' +
                'specific language governing permissions and limitations\n' +
                'under the License.\n' +
                '-->\n\n', '(# )|(\\[.*\\]\\(.*\\))'

    }

    format 'gradle', {
        target '*.gradle'

        licenseHeader '/*\n' +
                ' * Licensed to the Apache Software Foundation (ASF) under one or more\n' +
                ' * contributor license agreements.  See the NOTICE file distributed with\n' +
                ' * this work for additional information regarding copyright ownership.\n' +
                ' * The ASF licenses this file to You under the Apache License, Version 2.0\n' +
                ' * (the "License"); you may not use this file except in compliance with\n' +
                ' * the License.  You may obtain a copy of the License at\n' +
                ' *\n' +
                ' *      http://www.apache.org/licenses/LICENSE-2.0\n' +
                ' *\n' +
                ' * Unless required by applicable law or agreed to in writing, software\n' +
                ' * distributed under the License is distributed on an "AS IS" BASIS,\n' +
                ' * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n' +
                ' * See the License for the specific language governing permissions and\n' +
                ' * limitations under the License.\n' +
                ' */\n\n', '(.*\\{)|(.* = .*)|(apply plugin:)'
    }
}

repositories {
    // for access from China, you may need to uncomment this line
    // maven { url 'https://maven.aliyun.com/repository/public/' }
    mavenCentral()
    maven {
        url "https://repository.apache.org/content/repositories/snapshots/"
        mavenContent {
            snapshotsOnly()
        }
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    jvmArgs '--add-opens=java.base/java.util=ALL-UNNAMED'
}

sourceCompatibility = javaVersion
targetCompatibility = javaVersion
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// declare where to find the dependencies of your project
repositories {
    // for access from China, you may need to uncomment this line
    // maven { url 'https://maven.aliyun.com/repository/public/' }
    mavenCentral()
    maven {
        url "https://repository.apache.org/content/repositories/snapshots/"
        mavenContent {
            snapshotsOnly()
        }
    }
}

// common set of dependencies
dependencies {
    implementation "org.apache.logging.log4j:log4j-slf4j-impl:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-api:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-core:${log4jVersion}"

    implementation "org.apache.flink:flink-clients:${flinkVersion}"
    implementation "org.apache.flink:flink-java:${flinkVersion}"
    implementation "org.apache.flink:flink-streaming-java:${flinkVersion}"

    // common set for testing
    testImplementation "junit:junit:${junitVersion}"
    testImplementation "org.apache.flink:flink-streaming-java:${flinkVersion}:tests"
    testImplementation "org.apache.flink:flink-runtime:${flinkVersion}:tests"
    testImplementation "org.apache.flink:flink-test-utils-junit:${flinkVersion}"
    testImplementation "org.apache.flink:flink-test-utils:${flinkVersion}"
}

// add solution source dirs:
sourceSets {
    main.java.srcDirs += 'src/solution/java'

    // Add shadow configuration to runtime class path so that the
    // dynamically-generated tasks by IntelliJ are able to run and have
    // all dependencies they need. (Luckily, this does not influence what
    // ends up in the final shadowJar.)
    // TODO main.runtimeClasspath += configurations.shadow

    // TODO test.compileClasspath += configurations.shadow
    // TODO test.runtimeClasspath += configurations.shadow
}

project.plugins.withId('application') {
    ['javaExerciseClassName', 'javaSolutionClassName'].each { property ->
        createTrainingRunTask(project, property)
    }
}

spotless {
    java {
        googleJavaFormat().aosp()

        // \# refers to static imports
        importOrder('org.apache.flink', 'org.apache.flink.shaded', '', 'javax', 'java', '\\#')
        removeUnusedImports()

        targetExclude("**/generated*/**/*.java")

        licenseHeader '/*\n' +
                ' * Licensed to the Apache Software Foundation (ASF) under one\n' +
                ' * or more contributor license agreements.  See the NOTICE file\n' +
                ' * distributed with this work for additional information\n' +
                ' * regarding copyright ownership.  The ASF licenses this file\n' +
                ' * to you under the Apache License, Version 2.0 (the\n' +
                ' * "License"); you may not use this file except in compliance\n' +
                ' * with the License.  You may obtain a copy of the License at\n' +
                ' *\n' +
                ' *     http://www.apache.org/licenses/LICENSE-2.0\n' +
                ' *\n' +
                ' * Unless required by applicable law or agreed to in writing, software\n' +
                ' * distributed under the License is distributed on an "AS IS" BASIS,\n' +
                ' * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n' +
                ' * See the License for the specific language governing permissions and\n' +
                ' * limitations under the License.\n' +
                ' */\n\n'
    }
}

jar {
    manifest {
        attributes 'Built-By': System.getProperty('user.name'),
                'Build-Jdk': System.getProperty('java.version')
    }
}


static def void createTrainingRunTask(Project project, String property) {
    if (project.ext.has(property)) {
        project.tasks.create(name: classNamePropertyToTaskName(property), type: JavaExec) {
            classpath = project.sourceSets.main.runtimeClasspath
            mainClass = project.ext.get(property)
            jvmArgs = ['--add-opens=java.base/java.util=ALL-UNNAMED']
            group = 'flink-training-bootcamp'
        }
    }
}

static def String classNamePropertyToTaskName(String property) {
    return 'run' +
            property.charAt(0).toString().toUpperCase() +
            property.substring(1, property.lastIndexOf('ClassName'))

}