/*
 * Copyright (C) 2024 Ververica, Inc, Inc. All rights reserved.
 * This file is part of the Ververica Academy training software.
 */

plugins {
    id 'flink-training-developer'
}

dependencies {
    implementation project(path: ':common')
    testImplementation testFixtures(project(':common'))
}

// TODO - do I need this?
ext.javaExerciseClassName = 'org.apache.flink.training.exercises.ridecleansing.RideCleansingExercise'
ext.javaSolutionClassName = 'org.apache.flink.training.solutions.ridecleansing.RideCleansingSolution'
mainClassName = ext.javaExerciseClassName
